apiVersion: v1
kind: Service
metadata:
  name: k8s-cd-svc
  namespace: cd
spec:
  selector:
    app: k8s-cd
  ports:
    - name: http
      port: 8080        # Service 内部端口
      targetPort: 8080  # 容器端口
      nodePort: 30080   # 节点暴露端口（可选，不写则随机分配）
      protocol: TCP
  type: NodePort
  sessionAffinity: None